### PR TITLE
Fix searching for global busted install

### PR DESCRIPTION
**Pull request by MisanthropicBit**
~Need to verify paths since global install fails on my system.~ Fixed. Also enforce lua 5.1 for neovim.

### CODE REVIEW

**Comment by MisanthropicBit** [comment]
@YaroSpace This works on my machine with a system-wide install of busted. You’re welcome to test it out since you might be on a linux box or a mac with a different setup than mine.

**Comment by YaroSpace** [comment]
Sure.  Will do.

**Comment by MisanthropicBit** [comment]
@YaroSpace Did you get a chance to test this? 🙂

**Comment by YaroSpace** [comment]
Yes, everything seems to be fine.  Sorry, forgot to let you know earlier.

**Comment by MisanthropicBit** [comment]
Np. Thanks for testing it out.

**Pull request merged**
